### ISSUE TITLE
Snapshotter problem /bin/todo_snapshotter.php

### ISSUE THREAD

**Issue by citronbleuv** [prooph/proophessor-do#158]
I use a new install with branch expressive_3_0

When a run todo snapshotter with docker I have this error : 
> snapshotter_todo_1          | >> Waiting for MySql to start
snapshotter_todo_1          | >> MySql socket available, resuming command execution
snapshotter_todo_1          | 
snapshotter_todo_1          | Fatal error: Uncaught Prooph\EventSourcing\Aggregate\Exception\AggregateTypeException: Aggregate root must be an object but type of NULL given in /app/vendor/prooph/event-sourcing/src/Aggregate/AggregateType.php:37
snapshotter_todo_1          | Stack trace:
snapshotter_todo_1          | #0 /app/vendor/prooph/snapshotter/src/SnapshotReadModel.php(82): Prooph\EventSourcing\Aggregate\AggregateType::fromAggregateRoot(NULL)
snapshotter_todo_1          | #1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreReadModelProjector.php(770): Prooph\Snapshotter\SnapshotReadModel->persist()
snapshotter_todo_1          | #2 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreReadModelProjector.php(469): Prooph\EventStore\Pdo\Projection\PdoEventStoreReadModelProjector->persist()
snapshotter_todo_1          | #3 /app/vendor/prooph/snapshotter/src/StreamSnapshotProjection.php(36): Prooph\EventStore\Pdo\Projection\PdoEventStoreReadModelProjector->run(true)
snapshotter_todo_1          | #4 /app/bin/todo_snapshotter.php(49): Prooph\Snapshotter\StreamSnapshotProjection->__invoke()
snapshotter_todo_1          | #5 {main}
snapshotter_todo_1          |   thrown in /app/vendor/prooph/event-sourcing/src/Aggregate/AggregateType.php on line 37

I look in the SnapshotReadModel::persist() method and I have an User AggregateId in SnapshotReadModel::$aggregateCache 

So getAggregateRoot in line 80 return null because it's TodoListRepository.

**Comment by prolic** [comment]
@codeliner please check this as well. The problem comes from here:
https://github.com/prooph/snapshotter/blob/master/src/StreamSnapshotProjection.php

When using a single stream for all aggregates, we run into this issue. So we have a few options:
1) change proopessor-do to use one stream per aggregate type and note in the snapshotter repo, that the default provided implementations don't work for one stream for everything (that's the solution without much work)
2) update StreamSnapshotProjection and pass another argument to filter events upfront (maybe array key => value, where key = metadata key and value = metadata value, this way we can filter based on  `_aggregate_type` metadata key).
3) create a new SingleStreamForEverythingStreamSnapshotProjection implementation (whatever the name)

Better ideas? If not, which would you prefer?

**Comment by prolic** [comment]
ping @codeliner @oqq

**Comment by codeliner** [comment]
oh, totally missed that. Need to think about it. Option 1 sounds like a good first solution until we find a better way.

**Comment by prolic** [comment]
this is fixed is proophessor-do master by splitting streams, we still need a fix for the snapshotter.
