### ISSUE TITLE
Empty event_stream results in error in management UI

### ISSUE THREAD

**Issue by basz** [prooph/proophessor-do#159]
Minor I would say, but now we're at it.

After I boot the application + create the event_stream table and then load the management UI an error is presented (400 unknown). This goes away as soon as you create a User (it has an event)

**Comment by codeliner** [comment]
good catch. [ErrorCodeWhitelist](https://github.com/prooph/event-store-mgmt-ui/blob/master/src/EventStore/actions/queries.ts#L38) is missing for [GetLatestStreamEvents](https://github.com/prooph/event-store-mgmt-ui/blob/master/src/EventStore/actions/queries.ts#L20) query

It's caused by the http api which returns an error code for empty streams. /cc @prolic 
But solvable in the UI ;)

**Comment by basz** [comment]
though something along those lines. An empty event stream should not result in an error. But it may be that it's not empty just non-existant.

**Comment by prolic** [comment]
@codeliner the api should return a different error code. I think it's 404 VS 400.

**Comment by codeliner** [comment]
@prolic The request is `GET /stream/event_stream/head/backward/10`
and the Response: `400 '9223372036854775807' is not a valid event number`

The UI catches those 400 status code responses, but I missed the one for the initial query.
But maybe we should change the request handler to return a 404 instead?

**Comment by codeliner** [comment]
Solved in the latest version of the mgmt UI: https://github.com/prooph/proophessor-do/commit/abfbb91d25376c1b897bdd6972a34faf382e0d37
